document.addEventListener('DOMContentLoaded', async () => {
  // RATAINFO 16px
  try { for (const d of document.querySelectorAll('.card div')) { if (d.textContent.includes('Kalliopohjaisessa')) { d.style.fontSize='16px'; d.style.lineHeight='1.7'; d.style.color='#ccc'; } } } catch(e){}
  // TULOS + UNIIKIT yhdistetty
  try { const t=document.getElementById('live-kierrokset'); const u=document.getElementById('live-pelaajat'); if(t&&u){ const tc=t.closest('.card'); const uc=u.closest('.card'); if(tc&&uc&&tc!==uc&&!tc.dataset.combined){ tc.innerHTML=`<div style="flex:1;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:8px 0;"><div style="font-size:11px;font-weight:800;">UDISC & METRIX TULOSKIERROKSET - <span style="color:#00ff00;">AUTO 15/5MIN</span></div><div id="live-kierrokset" style="font-size:64px;font-weight:900;line-height:1;margin-top:8px;">${t.textContent}</div></div><div style="height:1px;background:#222;margin:8px 0;"></div><div style="flex:1;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:8px 0;"><div style="font-size:11px;font-weight:800;">UNIIKIT PELAAJAT - <span style="color:#00ff00;">AUTO</span></div><div id="live-pelaajat" style="font-size:64px;font-weight:900;line-height:1;margin-top:8px;">${u.textContent}</div></div>`; tc.dataset.combined='true'; tc.style.display='flex'; tc.style.flexDirection='column'; uc.innerHTML=`<div style="font-size:11px;font-weight:800;text-align:center;">HOLE IN ONE - <span style="color:#ffcc00;">MANUAALINEN</span></div><div id="hio-count" style="font-size:36px;font-weight:900;color:#ffcc00;margin:12px 0;text-align:center;">0</div><div id="hio-list" style="font-size:15px;font-weight:600;color:#ccc;line-height:1.8;text-align:center;">Ladataan HIO...</div>`; uc.style.borderLeft='3px solid #ffcc00'; } } } catch(e){}
  // TILASTO
  try { const r=await fetch('./data/tilasto.json?t='+Date.now()); if(r.ok){ const til=await r.json(); const set=(id,val)=>{ const el=document.getElementById(id); if(el) el.textContent=val; }; set('live-kierrokset',til.total||1130); set('live-pelaajat',til.unique||100); set('live-aika',til.playtime||'1004h'); set('live-askeleet',(til.steps||1300000).toLocaleString('fi-FI')); set('live-km',(til.km||970)+' km'); } } catch(e){}
  // TOP5 kaikki kolmella
  try { const r=await fetch('./data/top5.json?t='+Date.now()); if(r.ok){ const top=await r.json(); const PAR_44010=41,PAR_44763=82; const calc=(t,p)=>{ const d=t-p; return d>0?`+${d}`:d<0?`${d}`:'E'; }; const render=(id,arr,par)=>{ const el=document.getElementById(id); if(!el)return; if(!arr||!arr.length){ el.innerHTML='<li>Ei dataa</li>'; return; } let use=arr.filter(x=>!String(x.player).includes('Pelaaja A')); if(use.length==0) use=arr; use=use.map(x=>{ const tot=x.total||parseInt((x.display||'').match(/\d+/)?.[0]||0); return {...x,diff:tot-par,display:`${tot} (${calc(tot,par)})`}; }).sort((a,b)=>a.diff-b.diff); el.innerHTML=use.slice(0,5).map((x,i)=>`<li>${i+1}. ${x.player} ${x.display}</li>`).join(''); }; render('top5-44010',top.metrix_44010?.top5,PAR_44010); render('top5-44763',top.metrix_44763?.top5,PAR_44763); render('top5-udisc',top.udisc?.top5,PAR_44010); } } catch(e){ console.log('top5 err',e); }
  // SÄÄ 32px
  try { const sc=document.getElementById('saa-content'); if(sc){ const r=await fetch('./data/foreca.json?t='+Date.now()); if(r.ok){ const fc=await r.json(); if(fc.current){ sc.innerHTML=`<div style="display:flex;flex-direction:column;background:#0f0f0f;padding:12px;border-radius:8px;"><div style="display:flex;justify-content:space-between;"><div><div style="font-size:36px;font-weight:900;color:#fff;line-height:1;">${fc.current.temp}</div><div style="font-size:12px;color:#aaa;margin-top:4px;">Tuntuu ${fc.current.feels||''} ${fc.current.cloud||''}</div></div><div style="text-align:right;font-size:11px;color:#aaa;line-height:1.5;"><div>Tuuli ${fc.current.wind||''}</div><div>Puuskat ${fc.current.gust||''}</div><div style="color:#00ff00;font-weight:700;margin-top:6px;">Foreca LIVE</div></div></div><div style="display:flex;justify-content:space-between;margin-top:14px;border-top:1px solid #222;padding-top:12px;gap:4px;">${(fc.hourly||[]).map(h=>`<div style="text-align:center;flex:1;"><div style="font-size:11px;color:#888;margin-bottom:4px;">${h.hour}</div><div style="font-size:32px;margin:4px 0;line-height:1;">${h.icon||'☁️'}</div><div style="font-size:14px;color:#fff;font-weight:800;margin-top:2px;">${h.temp}°</div></div>`).join('')}</div></div>`; } } } } catch(e){}
  // HIO
  try { const r=await fetch('./data/holeinone.json?t='+Date.now()); if(r.ok){ const hio=await r.json(); const c=document.getElementById('hio-count'), l=document.getElementById('hio-list'); if(c) c.textContent=hio.count||hio.players?.length||0; if(l&&hio.players) l.innerHTML=hio.players.map(p=>`${p.player} #${p.hole}`).join('<br>'); } } catch(e){}
});
