name: DATA ONLY AUTO 5min

on:
  schedule:
    - cron: '*/5 * * * *' # joka 5min
  workflow_dispatch: # että voit painaa "Run workflow" nappia

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # että saa puskea takaisin
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Asenna kirjasto
        run: pip install matplotlib requests

      - name: Generoi DATA + PNG
        run: python scraper.py # <-- TÄSSÄ tapahtuu png generointi

      - name: Puske takaisin GitHubiin
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/tilasto.json data/top5.json data/ratatilasto.json vaylatilasto.png ratatilasto.png data/vaylatilasto.png data/ratatilasto.png
          git diff --staged --quiet || git commit -m "DATA ONLY 5min tiukka $(date +%H:%M)"
          git push
